/**
 * Renders the iOS PWA launch screens (`apple-touch-startup-image`). iOS matches
 * a splash by its media query; the image files must be the device's physical
 * pixel size. Files are generated by `scripts/generate-splash.mjs`
 * (`pnpm generate:splash`) — keep this list in sync with that script.
 *
 * The `<link>` tags render in the tree and React hoists them into `<head>`.
 */

interface StartupImage {
  src: string;
  deviceWidth: number;
  deviceHeight: number;
  ratio: number;
}

const STARTUP_IMAGES: StartupImage[] = [
  {
    src: "/splash/splash-1290x2796.png",
    deviceWidth: 430,
    deviceHeight: 932,
    ratio: 3,
  }, // iPhone 16 Pro Max, 15 Pro Max, 14 Pro Max
  {
    src: "/splash/splash-1179x2556.png",
    deviceWidth: 393,
    deviceHeight: 852,
    ratio: 3,
  }, // iPhone 16 Pro, 15 Pro, 14 Pro, 15, 14
  {
    src: "/splash/splash-1284x2778.png",
    deviceWidth: 428,
    deviceHeight: 926,
    ratio: 3,
  }, // iPhone 15 Plus, 14 Plus, 13 Pro Max, 12 Pro Max
  {
    src: "/splash/splash-1170x2532.png",
    deviceWidth: 390,
    deviceHeight: 844,
    ratio: 3,
  }, // iPhone 14, 13, 13 Pro, 12, 12 Pro
  {
    src: "/splash/splash-1125x2436.png",
    deviceWidth: 375,
    deviceHeight: 812,
    ratio: 3,
  }, // iPhone 13 mini, 12 mini, 11 Pro, X, XS
  {
    src: "/splash/splash-828x1792.png",
    deviceWidth: 414,
    deviceHeight: 896,
    ratio: 2,
  }, // iPhone 11, XR
  {
    src: "/splash/splash-750x1334.png",
    deviceWidth: 375,
    deviceHeight: 667,
    ratio: 2,
  }, // iPhone SE (2nd/3rd), 8, 7, 6s
  {
    src: "/splash/splash-640x1136.png",
    deviceWidth: 320,
    deviceHeight: 568,
    ratio: 2,
  }, // iPhone SE (1st), 5s, 5c
  {
    src: "/splash/splash-2048x2732.png",
    deviceWidth: 1024,
    deviceHeight: 1366,
    ratio: 2,
  }, // iPad Pro 12.9" (3rd gen+)
  {
    src: "/splash/splash-1668x2388.png",
    deviceWidth: 834,
    deviceHeight: 1194,
    ratio: 2,
  }, // iPad Pro 11" (1st gen+), iPad Air (4th/5th)
  {
    src: "/splash/splash-1620x2160.png",
    deviceWidth: 810,
    deviceHeight: 1080,
    ratio: 2,
  }, // iPad 10.2" (7th gen+), iPad (10th gen)
  {
    src: "/splash/splash-1536x2048.png",
    deviceWidth: 768,
    deviceHeight: 1024,
    ratio: 2,
  }, // iPad 9.7", iPad Air (1st/2nd), iPad mini (2nd-5th)
  {
    src: "/splash/splash-1488x2266.png",
    deviceWidth: 744,
    deviceHeight: 1133,
    ratio: 2,
  }, // iPad mini (6th gen)
  {
    src: "/splash/splash-1640x2360.png",
    deviceWidth: 820,
    deviceHeight: 1180,
    ratio: 2,
  }, // iPad Pro 13" (M4), iPad Air 13" (M2)
];

export function AppleStartupLinks() {
  return (
    <>
      {STARTUP_IMAGES.map(({ src, deviceWidth, deviceHeight, ratio }) => (
        <link
          key={src}
          rel="apple-touch-startup-image"
          href={src}
          media={`(device-width: ${deviceWidth}px) and (device-height: ${deviceHeight}px) and (-webkit-device-pixel-ratio: ${ratio})`}
        />
      ))}
    </>
  );
}
